### ISSUE TITLE
Success and some issues with hosting on GCP App Engine

### ISSUE THREAD

**Issue by CoreyH** [aaronn/slack-gpt#2]
I successfully set this up today on GCP App Engine standard using this as my app.yaml file:

```
runtime: python311

env_variables:
  OPENAI_API_KEY: 'sk-xxxxx'
  SLACK_APP_TOKEN: 'xapp-xxxxxx'
  SLACK_BOT_TOKEN: 'xoxb-xxxxxx'
  MODEL: 'gpt-4'

handlers:
- url: /.*
  script: auto

entrypoint: python slackgpt.py

instance_class: F1

```

Yay! 

The only problem is it seems to go to sleep pretty quickly and as I only have a few users on the system it doesn't want to come back automatically. I have been hitting the url endpoint manually to wake it back up. 

If anyone has suggestions please let me know.
